# Generated by Django 5.1.6 on 2025-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='voter_status',
            field=models.BooleanField(default=False),
        ),
    ]
