# Generated by Django 5.1.7 on 2025-03-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0005_alter_complaint_model_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casefile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('caseid', models.CharField(blank=True, max_length=100, null=True)),
                ('crime', models.CharField(blank=True, max_length=100, null=True)),
                ('adhaar_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='criminals/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evoteapp.user_model')),
            ],
        ),
    ]
