# Generated by Django 5.1.7 on 2025-03-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0008_alter_vote_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votingtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electiondate', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
