# Generated by Django 5.1.7 on 2025-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0009_publishstatus_votingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishstatus',
            name='status',
            field=models.CharField(choices=[('true', 'Publish'), ('false', 'Unpublish')], default='false', max_length=5),
        ),
    ]
