# Generated by Django 5.1.7 on 2025-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0010_alter_publishstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingtime',
            name='electiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votingtime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votingtime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
