# Generated by Django 5.1.6 on 2026-02-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evoteapp', '0011_alter_votingtime_electiondate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercandidatecode',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='usercandidatecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergroupmapping',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroupmapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='previous_hash',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_hash',
        ),
        migrations.DeleteModel(
            name='Candidatecode_model',
        ),
        migrations.DeleteModel(
            name='UserCandidateCode',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserGroupMapping',
        ),
    ]
